service:
  parsers_file: parsers.conf

pipeline:
  inputs:
    - name: tail
      path: input/EmployeeSalaries_*.csv
      parser: salaries_parser
      read_from_head: true
      tag: salaries

    - name: tail
      path: input/StudentsPerformance_*.csv
      parser: student_parser
      read_from_head: true
      tag: student

  filters:
    - name: wasm
      match: '*'
      wasm_path: filter_dp.wasm
      function_name: filter_dp
      accessible_paths: filters

  outputs:
    - name: file
      path: output/
      file: StudentsPerformance.perturbed.csv
      match: student
      format: template
      template: "{time},{gender},{race_ethnicity},{parental_education},{lunch},{test_preparation},{math_score},{reading_score},{writing_score}"

    - name: file
      path: output/
      file: EmployeeSalaries.perturbed.csv
      match: salaries
      format: template
      template: "{time},{Department},{Department_Name},{Division},{Gender},{Base_Salary},{Overtime_Pay},{Longevity_Pay},{Grade}"

    - name: stdout
      match: '*'