[package]
name = "filter_dp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rv = {version = "0.16", features = ["datum"]}
toml = "0.8"
rand = "0.8"
anyhow = "1.0"
