[Example1]
type = "Gaussian"
epsilon = 1.2
sensitivity = 1.4
delta = 0.98

[Example2]
type = "Laplace"
mu = 0.5
epsilon = 1.1
sensitivity = 1.5

[Example3]
type = "Laplace"
epsilon = 1
sensitivity = 1
rng_seed = "Test"